on: 
    push:
        branches:
            - develop
            - master
    pull_request:
        branches:
            - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Dotnet Side by Side testing sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '2.2.103'
      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '3.1.x'

      - name: Building the project
        run: dotnet build --configuration Release

      - name: Running the tests
        run: dotnet test --configuration Release